# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxwdqBIr2kNQDYIPUJ-Hzdvq3C1K6ONB
"""

pip install flask-cors

from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import numpy as np

app = Flask(__name__)
CORS(app)

# ✅ Load model + encoders (LOCAL PATH)
model = joblib.load("saved_model.pkl")
le_crop = joblib.load("crop_encoder.pkl")
le_district = joblib.load("district_encoder.pkl")

# 🔍 Debug (run once)
print("Crop classes:", le_crop.classes_)
print("District classes:", le_district.classes_)

@app.route("/")
def home():
    return "✅ Flask App Running"

@app.route("/predict", methods=["POST"])
def predict():
    try:
        data = request.json

        # ✅ Fix case automatically
        crop = data["crop"].strip().title()
        district = data["district"].strip().title()

        rainfall = float(data["rainfall"])
        temperature = float(data["temperature"])
        soil = float(data["soil"])
        humidity = float(data["humidity"])

        print("Received Crop:", crop)
        print("Received District:", district)

        # ✅ Encode
        crop_encoded = le_crop.transform([crop])[0]
        district_encoded = le_district.transform([district])[0]

        # ✅ Feature order (must match training)
        features = np.array([[crop_encoded, district_encoded,
                              rainfall, temperature, soil, humidity]])

        prediction = model.predict(features)[0]

        return jsonify({
            "predicted_yield": round(prediction, 2)
        })

    except Exception as e:
        print("Error:", str(e))
        return jsonify({"error": str(e)})

import os

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)